import streamlit as st
import pandas as pd
from data_fetch import fetch_historical_data, compute_stats
from optimizer import fetch_optimal_weights, calculate_rebalance_trades, calculate_contribution_trades
from tax_utils import estimate_taxes
from viz import plot_allocation_comparison, plot_efficient_frontier, plot_monte_carlo_simulations
from ai_summary import generate_trade_rationale
from monte_carlo import run_monte_carlo_simulation
import numpy as np

st.set_page_config(page_title="AI Rebalancer Prototype", layout="wide")

# -------- Sidebar: Portfolio Setup --------
st.sidebar.title("AI Portfolio Rebalancer")
st.sidebar.markdown("Upload your clients' portfolio to generate optimized trade recommendations.")

uploaded_file = st.sidebar.file_uploader("Upload Portfolio (CSV/TSV)", type=['csv', 'tsv'])

st.sidebar.markdown("---")
# Phase 2: SWAN Risk Toggle
swan_risk = st.sidebar.select_slider(
    "Sleep Well At Night (SWAN) Risk Tolerance",
    options=["Conservative", "Moderate", "Aggressive"],
    value="Moderate",
    help="Determines the minimum ETF allocation and maximum single-stock concentration."
)

# Map human risk to math constraints
if swan_risk == "Conservative":
    min_etf_weight = 0.80
    reg_gamma = 0.10  # Strict regularization, highly diversified
elif swan_risk == "Moderate":
    min_etf_weight = 0.60
    reg_gamma = 0.01  # Standard
else: # Aggressive
    min_etf_weight = 0.20
    reg_gamma = 0.001 # Let the AI make concentrated single-stock bets

st.sidebar.markdown("---")
new_deposit = st.sidebar.number_input(
    "Contribution Optimization: New Deposit ($)", 
    min_value=0.0, 
    value=0.0, 
    step=100.0,
    help="If greater than 0, the AI will build the portfolio toward optimal using ONLY this cash, avoiding any taxable sells."
)
target_account = st.sidebar.selectbox("Contribution Target Account", ["TFSA", "RRSP", "FHSA", "CASH/MARGIN"], index=0)

st.sidebar.markdown("---")
tax_bracket = st.sidebar.selectbox(
    "Estimated Tax Bracket", 
    [0.20, 0.30, 0.40, 0.50], 
    index=2,
    help="Used to estimate the tax hit on capital gains generated by rebalancing trades."
)

st.sidebar.markdown("---")
api_key = st.sidebar.text_input("Google Gemini API Key (Optional)", type="password", help="Enter a Gemini API key to generate conversational trade summaries.")


if uploaded_file is not None:
    # Infer separator safely
    try:
        portfolio_df = pd.read_csv(uploaded_file)
        # If it only parsed 1 column, it might be a TSV
        if len(portfolio_df.columns) == 1:
            uploaded_file.seek(0)
            portfolio_df = pd.read_csv(uploaded_file, sep='\t')
            
        portfolio_df.columns = portfolio_df.columns.str.strip()
    except Exception as e:
        st.error(f"Could not read the uploaded portfolio file: {e}")
        st.stop()
        
    st.title("AI Portfolio Rebalancer")

    # -------- 1. Process Current Holdings --------
    current_holdings = {}
    for _, row in portfolio_df.iterrows():
        current_holdings[row['ticker']] = {
            'shares': row['shares'],
            'cost_basis': row['avg_cost'],
            'account_type': row['account_type']
        }
        
    tickers = list(current_holdings.keys())
    
    st.subheader(f"Analyzing {len(tickers)} Assets...")
    
    # Fetch all underlying financial data
    with st.spinner("Fetching historical market data from Yahoo Finance..."):
        tickers_data, current_prices = fetch_historical_data(tickers)
        
    if tickers_data is not None:
        
        # -------- 2. AI Optimization Engine --------
        try:
            mu, S = compute_stats(tickers_data)
        except Exception as e:
            st.error(f"Error computing portfolio statistics: {e}")
            st.stop()
        
        # Determine ETFs heuristically (or user input in a real product)
        # For prototype, we'll arbitrarily assume everything ending in 'EQT' or 'SP' or 'NQ' is an ETF
        etf_tickers = [t for t in tickers if 'EQT' in t or 'SP' in t or 'NQ' in t or 'VDY' in t]
        
        # Run Mathematical Optimization using SWAN Parameters
        optimal_weights = fetch_optimal_weights(
            mu, S, 
            regularization_gamma=reg_gamma, 
            min_etf_weight=min_etf_weight, 
            etf_tickers=etf_tickers
        )
        
        
        current_weights_pct = {}
        total_val = sum(current_holdings[t]['shares'] * current_prices.get(t,0) for t in tickers)
        for t in tickers:
            current_weights_pct[t] = (current_holdings[t]['shares'] * current_prices.get(t,0)) / total_val if total_val > 0 else 0
            
        # UI Tab Layout
        tab1, tab2, tab3, tab4 = st.tabs(["AI Trades & Tax", "Risk / Return Math", "Current Input", "Monte Carlo Simulation"])
        
        with tab1:
            # -------- 3. Rebalancer Output --------
            st.markdown(f"### Recommended Actions ({swan_risk} Setting)")
            
            if new_deposit > 0:
                trades, remaining_cash = calculate_contribution_trades(current_holdings, optimal_weights, current_prices, new_deposit, target_account)
                st.info(f"Contribution Mode Active: Spending ${new_deposit:,.2f} without selling any existing positions. Remaining unspent cash: **${remaining_cash:,.2f}**")
                tax_report = {'taxable_gains': 0.0, 'total_estimated_tax': 0.0, 'tax_free_gains': 0.0, 'account_breakdown': {}}
            else:
                drift = st.slider("Drift Threshold required to trigger trade (%)", 1, 15, 5, help="Only generate trades if an asset's weight drifts further than this threshold.") / 100.0
                trades = calculate_rebalance_trades(current_holdings, optimal_weights, current_prices, drift_threshold=drift)
            
            if len(trades) > 0:
                trade_df = pd.DataFrame(trades)
                
                # Highlight BUYS in green, SELLS in red using pandas styling
                def color_action(val):
                    color = '#27ae60' if val == 'BUY' else '#c0392b'
                    return f'color: {color}; font-weight: bold;'
                    
                # Format dataframe columns
                formatted_df = trade_df.style.applymap(color_action, subset=['action']) \
                                       .format({
                                           'est_gain': '${:,.2f}',
                                           'current_weight': '{:.2%}',
                                           'target_weight': '{:.2%}',
                                           'shares': '{:,.4f}' if new_deposit > 0 else '{:,.0f}'
                                       })
                    
                st.dataframe(formatted_df, use_container_width=True)
                
                # -------- 4. Compute Tax Preview --------
                st.markdown("### Canadian Tax Preview")
                if new_deposit <= 0:
                    tax_report = estimate_taxes(trades, tax_bracket_rate=tax_bracket)
                
                col1, col2, col3 = st.columns(3)
                col1.metric("Est. Taxable Gains", f"${tax_report['taxable_gains']:,}")
                col2.metric("Total Tax Hit (50% rule)", f"${tax_report['total_estimated_tax']:,}", delta_color="inverse")
                col3.metric("Total Sheltered Gains", f"${tax_report['tax_free_gains']:,}")
                
                if new_deposit <= 0 and 'account_breakdown' in tax_report and len(tax_report['account_breakdown']) > 0:
                    with st.expander("View Breakdown by Account Type"):
                        for acc, data in tax_report['account_breakdown'].items():
                            if acc in ['TFSA', 'RRSP', 'FHSA']:
                                st.write(f"✅ **{acc} (Sheltered)**: ${data['gains']:,} in tax-free gains.")
                            else:
                                st.write(f"⚠️ **{acc} (Taxable)**: ${data['gains']:,} in gains ➔ **${data['estimated_tax']:,}** estimated tax.")
                
                # -------- 5. AI Summary Translation --------
                if api_key:
                    with st.expander("✨ Translate this to human (Gemini AI Summary)", expanded=True):
                        with st.spinner("Gemini is analyzing the trades..."):
                            explanation = generate_trade_rationale(api_key, trades, tax_report if new_deposit <= 0 else "No Tax Hit (Contribution Only)")
                            st.write(explanation)
                else:
                    st.info("💡 Tip: Enter a Gemini API Key in the sidebar to get a human-friendly AI translation of these trades!")
                
            else:
                st.success("Your portfolio is currently optimal and within the accepted drift thresholds!")

            st.plotly_chart(plot_allocation_comparison(current_weights_pct, optimal_weights), use_container_width=True)

        with tab2:
            st.markdown("### The Efficient Frontier")
            st.plotly_chart(plot_efficient_frontier(mu, S, optimal_weights), use_container_width=True)
            
        with tab3:
            st.markdown("### Processed Input Data")
            formatted_input_df = portfolio_df.style.format({'avg_cost': '${:,.2f}', 'shares': '{:,.0f}'})
            st.dataframe(formatted_input_df, use_container_width=True)
            
        with tab4:
            st.markdown("### 1-Year Future Projections")
            st.markdown("Using your AI Optimal Weights and historical volatility, we project 1000 simulated paths for your portfolio over the next 252 trading days.")
            
            with st.spinner("Running 1000 Monte Carlo permutations..."):
                simulated_paths = run_monte_carlo_simulation(total_val, optimal_weights, mu, S, days=252, num_sims=1000)
                
            st.plotly_chart(plot_monte_carlo_simulations(simulated_paths), use_container_width=True)
            
            # Additional metrics
            final_values = simulated_paths[-1, :]
            col1, col2, col3 = st.columns(3)
            col1.metric("Worst Case (5th %)", f"${np.percentile(final_values, 5):,.0f}")
            col2.metric("Expected (Median)", f"${np.median(final_values):,.0f}")
            col3.metric("Best Case (95th %)", f"${np.percentile(final_values, 95):,.0f}")
            
else:
    st.info("Awaiting Portfolio CSV Upload...")
